import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
//       <body className={inter.className}>{children}</body> 폰트적용되는거임

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* max-w-screen이랑 mx-auto는 set로 기억하면 좋음 */}
      <body className={`${inter.className} max-w-screen-sm mx-auto`}>
        {children}
      </body>
    </html>
  );
}
